title: Naše cesty
description: Přehled plánovaných a připravovaných cest
theme: jekyll-theme-cayman

# Volitelné - pokud budete chtít, aby se pod title zobrazoval podnadpis
# na hlavní stránce (u tématu cayman se to bere z description výše).
